### ISSUE TITLE
Error when logging empty string

### ISSUE THREAD

**Issue by matthewoates** [caiogondim/logdown.js#229]
```
matt@refuge ~/w/t/tools (master)> cat example.js
require('process').env.NODE_DEBUG = '*';

const logger = require('logdown')('example');

logger.log('');
matt@refuge ~/w/t/tools (master)> node example.js
/home/matt/workspace/tradr/tools/node_modules/logdown/src/markdown/Markdown.js:36
  while (lexeme = lexemes[cursor]) { // eslint-disable-line
                         ^

TypeError: Cannot read property '0' of null
    at Markdown.parse (/home/matt/workspace/tradr/tools/node_modules/logdown/src/markdown/Markdown.js:36:26)
    at Object.parse (/home/matt/workspace/tradr/tools/node_modules/logdown/src/markdown/node.js:14:20)
    at Logdown.<anonymous> (/home/matt/workspace/tradr/tools/node_modules/logdown/src/node.js:122:38)
    at Array.forEach (<anonymous>)
    at Logdown._prepareOutput (/home/matt/workspace/tradr/tools/node_modules/logdown/src/node.js:119:8)
    at Logdown.instance.<computed> [as log] matt@refuge ~/w/t/tools (master)> cat example.js
require('process').env.NODE_DEBUG = '*';

const logger = require('logdown')('example');

logger.log('');
matt@refuge ~/w/t/tools (master)> node example.js
/home/matt/workspace/tradr/tools/node_modules/logdown/src/markdown/Markdown.js:36
  while (lexeme = lexemes[cursor]) { // eslint-disable-line
                         ^

TypeError: Cannot read property '0' of null
    at Markdown.parse (/home/matt/workspace/tradr/tools/node_modules/logdown/src/markdown/Markdown.js:36:26)
    at Object.parse (/home/matt/workspace/tradr/tools/node_modules/logdown/src/markdown/node.js:14:20)
    at Logdown.<anonymous> (/home/matt/workspace/tradr/tools/node_modules/logdown/src/node.js:122:38)
    at Array.forEach (<anonymous>)
    at Logdown._prepareOutput (/home/matt/workspace/tradr/tools/node_modules/logdown/src/node.js:119:8)
    at Logdown.instance.<computed> [as log] (/home/matt/workspace/tradr/tools/node_modules/logdown/src/base.js:130:39)
    at Object.<anonymous> (/home/matt/workspace/tradr/tools/example.js:5:8)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)(/home/matt/workspace/tradr/tools/node_modules/logdown/src/base.js:130:39)
    at Object.<anonymous> (/home/matt/workspace/tradr/tools/example.js:5:8)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
```

**Comment by matthewoates** [comment]
```
matt@refuge ~/w/t/tools (master)> node --version
v12.16.1
matt@refuge ~/w/t/tools (master)> npm ls
tools@1.0.0 /home/matt/workspace/tradr/tools
├─┬ logdown@3.3.0
```

**Comment by caiogondim** [comment]
I can reproduce it. 
Working on a fix.

**Comment by caiogondim** [comment]
New version published https://www.npmjs.com/package/logdown
